### ISSUE TITLE
After update to latest commit

### ISSUE THREAD

**Issue by jango-blockchained** [Spare-Network/spare-blockchain#107]
Traceback (most recent call last):
  File "/root/clx-chia-multi-setup/spare-blockchain/venv/bin/spare_full_node", line 33, in <module>
    sys.exit(load_entry_point('spare-blockchain', 'console_scripts', 'spare_full_node')())
  File "/root/clx-chia-multi-setup/spare-blockchain/venv/bin/spare_full_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/clx-chia-multi-setup/spare-blockchain/spare/server/start_full_node.py", line 8, in <module>
    from spare.full_node.full_node import FullNode
  File "/root/clx-chia-multi-setup/spare-blockchain/spare/full_node/full_node.py", line 62, in <module>
    class FullNode:
  File "/root/clx-chia-multi-setup/spare-blockchain/spare/full_node/full_node.py", line 341, in FullNode
    async def new_peak(self, request: full_node_protocol.NewPeak, peer: ws.WSChiaConnection):
AttributeError: module 'spare.server.ws_connection' has no attribute 'WSChiaConnection'

**Comment by sanok2000** [comment]
I got this

ConnectionResetError: Cannot write to closing transport
2021-07-19T11:39:18.468 harvester harvester               : INFO     Reconnecting to peer {'host': '127.0.0.1', 'port': 9447}
2021-07-19T11:39:18.489 harvester harvester_server        : ERROR    Exception name 'WSChiaConnection' is not defined, exception Stack: Traceback (most recent call last):
  File "spare/server/server.py", line 377, in start_client
NameError: name 'WSChiaConnection' is not defined

**Comment by Jsewill** [comment]
I can confirm the same issue as @jango-blockchained

**Comment by Jsewill** [comment]
I've submitted a pull request (#110) that seems to correct this particular issue.
