### ISSUE TITLE
Exception name 'WSChiaConnection' is not defined

### ISSUE THREAD

**Issue by mircot80** [Spare-Network/spare-blockchain#108]
2021-07-19T20:06:25.837 harvester asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished name='Task-17137' coro=<WebSocketWriter.ping() done, defined at /home/mirco/spare-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py:669> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/home/mirco/spare-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 673, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/home/mirco/spare-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 643, in _send_frame
    self._write(header + mask + message)
  File "/home/mirco/spare-blockchain/venv/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 660, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2021-07-19T20:06:25.922 harvester harvester_server        : ERROR    Exception name 'WSChiaConnection' is not defined, exception Stack: Traceback (most recent call last):
  File "/home/mirco/spare-blockchain/spare/server/server.py", line 377, in start_client
    connection = WSChiaConnection(
NameError: name 'WSChiaConnection' is not defined

**Comment by jango-blockchained** [comment]
As workaround you can checkout some commits before:

cd spare-blockchain
. ./activate
spare stop -d all
deactivate
git checkout dbd5524cd86c6626f2349d279783a90b064a30a5
sh install.sh
. ./activate
spare init
spare start -r farmer
sleep 30s
spare wallet show
deactivate

**Comment by mircot80** [comment]
it works, now it's syncing, thanks.
