### ISSUE TITLE
Install spare and error after spare start farmer

### ISSUE THREAD

**Issue by stanchiam** [Spare-Network/spare-blockchain#112]
Traceback (most recent call last):
  File "/home/smv/spare-blockchain/venv/bin/spare_full_node", line 33, in <module>
    sys.exit(load_entry_point('spare-blockchain', 'console_scripts', 'spare_full_node')())
  File "/home/smv/spare-blockchain/venv/bin/spare_full_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smv/spare-blockchain/spare/server/start_full_node.py", line 8, in <module>
    from spare.full_node.full_node import FullNode
  File "/home/smv/spare-blockchain/spare/full_node/full_node.py", line 62, in <module>
    class FullNode:
  File "/home/smv/spare-blockchain/spare/full_node/full_node.py", line 341, in FullNode
    async def new_peak(self, request: full_node_protocol.NewPeak, peer: ws.WSChiaConnection):
AttributeError: module 'spare.server.ws_connection' has no attribute 'WSChiaConnection'

**Comment by behrendsr** [comment]
Same problem over here:
`spaTraceback (most recent call last):
  File "/home/spare/spare-blockchain/venv/bin/spare_full_node", line 33, in <module>
    sys.exit(load_entry_point('spare-blockchain', 'console_scripts', 'spare_full_node')())
  File "/home/spare/spare-blockchain/venv/bin/spare_full_node", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/spare/spare-blockchain/spare/server/start_full_node.py", line 8, in <module>
    from spare.full_node.full_node import FullNode
  File "/home/spare/spare-blockchain/spare/full_node/full_node.py", line 62, in <module>
    class FullNode:
  File "/home/spare/spare-blockchain/spare/full_node/full_node.py", line 341, in FullNode
    async def new_peak(self, request: full_node_protocol.NewPeak, peer: ws.WSChiaConnection):
AttributeError: module 'spare.server.ws_connection' has no attribute 'WSChiaConnection'
`

**Comment by stanchiam** [comment]
managed to resolve it by editing 2 files
(\spare-blockchain\spare\full_node) full_node.py line 341, change to WSspareConnection
(\spare-blockchain\spare\server) server.py line 377 change to WSspareConnection
then restart spare

**Comment by behrendsr** [comment]
> managed to resolve it by editing 2 files
> (\spare-blockchain\spare\full_node) full_node.py line 341, change to WSspareConnection
> (\spare-blockchain\spare\server) server.py line 377 change to WSspareConnection
> then restart spare

That worked. Thanks.

**Comment by smitt1979** [comment]
> managed to resolve it by editing 2 files
> (\spare-blockchain\spare\full_node) full_node.py line 341, change to WSspareConnection
> (\spare-blockchain\spare\server) server.py line 377 change to WSspareConnection
> then restart spare

Top Man fix it for me to 

Update 

Found second that needs changing in /spare-blockchain/spare/full_node/full_node.py  line 341 change to **WSspareConnection**
