### ISSUE TITLE
harvesters are banning farmer...

### ISSUE THREAD

**Issue by Trypt88** [Spare-Network/spare-blockchain#114]
2021-07-31T11:57:21.715 harvester spare.server.rate_limits: WARNING  Invalid message: 66, 66 is not a valid ProtocolMessageTypes
2021-07-31T11:57:21.715 harvester harvester_server        : ERROR    Exception: 66 is not a valid ProtocolMessageTypes <class 'ValueError'>, closing connection {'host': '192.168.1.77', 'port': 9447}. ValueError: 66 is not a valid ProtocolMessageTypes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spare\server\server.py", line 493, in api_call
  File "C:\Users\maxca\AppData\Local\Programs\Python\Python37\lib\enum.py", line 310, in __call__
  File "C:\Users\maxca\AppData\Local\Programs\Python\Python37\lib\enum.py", line 564, in __new__
  File "C:\Users\maxca\AppData\Local\Programs\Python\Python37\lib\enum.py", line 548, in __new__
  File "C:\Users\maxca\AppData\Local\Programs\Python\Python37\lib\enum.py", line 577, in _missing_
ValueError: 66 is not a valid ProtocolMessageTypes

2021-07-31T11:57:21.719 harvester harvester_server        : INFO     Connection closed: 192.168.1.77, node id: c313cd76a8f34998a5ff210627229c8335d16ccf164f904e847a957b10e89696
2021-07-31T11:57:21.720 harvester harvester_server        : WARNING  Banning 192.168.1.77 for 10 seconds
2021-07-31T11:57:21.721 harvester spare.harvester.harvester: INFO     peer disconnected {'host': '192.168.1.77', 'port': 9447}
2021-07-31T11:57:24.023 harvester harvester               : INFO     Reconnecting to peer {'host': '192.168.1.77', 'port': 9447}
2021-07-31T11:57:24.023 harvester harvester_server        : WARNING  Peer 192.168.1.77 is still banned, not connecting to it

**Comment by Trypt88** [comment]
Ok, problem solved... So you upgraded the Spare package to 0.1.dev82, but your windows build for download is still 1.1.7... Who ever upgraded Spare to the latest, must build windows to 0.1.dev82 too, download from the provided link won't work.

**Comment by Trypt88** [comment]
Hmm, more issues... So a clean build of 0.1.dev82 on windows, cannot spare init, there's no certs in the ssl folder of venv... I need to manually download the blockchain zip and copy to the blockchain folder in the venv... 

(venv) PS C:\Users\USER\forks\spare-blockchain> spare init
Spare directory C:\Users\USER\.spare-blockchain\mainnet
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\forks\spare-blockchain\venv\scripts\spare.exe\__main__.py", line 7, in <module>
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\spare\cmds\spare.py", line 79, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\spare\cmds\init.py", line 30, in init_cmd
    init(Path(create_certs) if create_certs is not None else None, ctx.obj["root_path"])
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\spare\cmds\init_funcs.py", line 254, in init
    return spare_init(root_path)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\spare\cmds\init_funcs.py", line 333, in spare_init
    create_all_ssl(root_path)
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\spare\cmds\init_funcs.py", line 179, in create_all_ssl
    spare_ca_crt, spare_ca_key = get_spare_ca_crt_key()
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\spare\ssl\create_ssl.py", line 15, in get_spare_ca_crt_key
    crt = pkg_resources.resource_string(__name__, "spare_ca.crt")
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\pkg_resources\__init__.py", line 1142, in resource_string
    return get_provider(package_or_requirement).get_resource_string(
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\pkg_resources\__init__.py", line 1388, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "c:\users\user\forks\spare-blockchain\venv\lib\site-packages\pkg_resources\__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\user\\forks\\spare-blockchain\\venv\\lib\\site-packages\\spare\\ssl\\spare_ca.crt'
(venv) PS C:\Users\USER\forks\spare-blockchain>
