### ISSUE TITLE
Full-Node error

### ISSUE THREAD

**Issue by bobiobobhead** [Spare-Network/spare-blockchain#118]
Hi, was wondering if anyone is able to help with this?  Full node runs for a couple of hours and then all services stop, cli shows this error message.  When it's running its fine works as expected I have won a block even.

Starting daemon
spare_harvester: started
spare_farmer: started
spare_full_node: started
spare_wallet: started
Traceback (most recent call last):
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 574, in run_until_complete
  File "asyncio\base_events.py", line 541, in run_forever
  File "asyncio\base_events.py", line 1750, in _run_once
  File "selectors.py", line 323, in select
  File "selectors.py", line 314, in _select
ValueError: too many file descriptors in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spare\server\start_full_node.py", line 65, in <module>
  File "spare\server\start_full_node.py", line 60, in main
  File "spare\server\start_service.py", line 234, in run_service
  File "asyncio\runners.py", line 46, in run
  File "asyncio\runners.py", line 62, in _cancel_all_tasks
  File "asyncio\base_events.py", line 574, in run_until_complete
  File "asyncio\base_events.py", line 541, in run_forever
  File "asyncio\base_events.py", line 1750, in _run_once
  File "selectors.py", line 323, in select
  File "selectors.py", line 314, in _select
ValueError: too many file descriptors in select()
[6284] Failed to execute script start_full_node

**Comment by bobiobobhead** [comment]
I was able to fix this by editing the config file where it shows "target_peer_count: 800" I have adjsuted this to 80, this is now the same as chia and other forks and working fine.
