### ISSUE TITLE
Wallet Not Synced

### ISSUE THREAD

**Issue by Ratchanida** [Spare-Network/spare-blockchain#122]
My Spare Gui has been working fine and earning rewards often for the past 2 months.  The wallet has just experienced syncing issue recently.  The Full Node status shows that it is synced but the wallet is not synced.  Has anyone experienced the same issue and know how to fix this?  Much appreciated :) 

![spare wallet](https://user-images.githubusercontent.com/86420352/133103442-029ed140-9f5b-4c7c-8a27-efbaecc4dece.JPG)
![spare full nodeJPG](https://user-images.githubusercontent.com/86420352/133103461-0d689dcc-6e55-4a10-804c-888a06840055.JPG)

**Comment by grayfallstown** [comment]
Please check if you find this error in spares debug log file as well, as it seems to be the reason why my wallet stopped syncing, too:

```
2021-09-12T09:01:26.874 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 10608}. Traceback (most recent call last):
  File "spare\server\server.py", line 526, in wrapped_coroutine
  File "spare\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "spare\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "spare\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "spare\consensus\blockchain.py", line 695, in get_block_records_at
  File "spare\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables
```

**Comment by Ratchanida** [comment]
> Please check if you find this error in spares debug log file as well, as it seems to be the reason why my wallet stopped syncing, too:
> 
> ```
> 2021-09-12T09:01:26.874 full_node full_node_server        : ERROR    Exception: too many SQL variables, {'host': '127.0.0.1', 'port': 10608}. Traceback (most recent call last):
>   File "spare\server\server.py", line 526, in wrapped_coroutine
>   File "spare\full_node\full_node_api.py", line 244, in request_proof_of_weight
>   File "spare\full_node\weight_proof.py", line 77, in get_proof_of_weight
>   File "spare\full_node\weight_proof.py", line 119, in _create_proof_of_weight
>   File "spare\consensus\blockchain.py", line 695, in get_block_records_at
>   File "spare\full_node\block_store.py", line 181, in get_block_records_by_hash
>   File "aiosqlite\core.py", line 184, in execute
>   File "aiosqlite\core.py", line 129, in _execute
>   File "aiosqlite\core.py", line 102, in run
> sqlite3.OperationalError: too many SQL variables
> ```
Thanks you
I have the same error  ERROR    "Exception: too many SQL variables"  and how should I fix this? Thanks

**Comment by grayfallstown** [comment]
no idea

**Comment by Ratchanida** [comment]
Anyone know how to fix this issue? Please help.

**Comment by Ratchanida** [comment]
My debug.log shows below, Does anyone know how to fix this, please?  Much appreciated.

2021-09-20T20:16:25.546 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '127.0.0.1', 'port': 9449}. Traceback (most recent call last):
  File "spare\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "spare\server\server.py", line 533, in wrapped_coroutine
  File "spare\server\server.py", line 526, in wrapped_coroutine
  File "spare\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "spare\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "spare\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "spare\consensus\blockchain.py", line 695, in get_block_records_at
  File "spare\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

2021-09-20T20:16:25.547 full_node full_node_server        : WARNING  Trying to ban localhost for 10, but will not ban
2021-09-20T20:16:28.430 full_node asyncio                 : ERROR    Task exception was never retrieved
future: <Task finished coro=<SpareServer.incoming_api_task.<locals>.api_call() done, defined at spare\server\server.py:487> exception=CancelledError()>
concurrent.futures._base.CancelledError

**Comment by Ratchanida** [comment]
I decided to delete .spare-blockchain folders and re-installed Spare Blockchain software.  First time I did the reinstallation, no node connections seemed to synced up. So I had to re-install the software and restart my computer again.  This time it works. Yes! IT WORKS. My full node and wallet are now synced and still running.  I've also earned my missing block rewards. (for over 10 days that the wallet status showed not synced) Wondering what the latest Spare software version that other farmers are using currently? It shows on mine version 0.1.1
