### ISSUE TITLE
too many SQL variables

### ISSUE THREAD

**Issue by OldButtKicking** [Spare-Network/spare-blockchain#124]
This is the error I am seeing every 5-6 min in the log. What does it mean and should I be concerned? Needless to say I have not won in weeks and est is 3-4 days.
2021-09-15T03:52:53.184 full_node full_node_server        : ERROR    Exception: too many SQL variables <class 'sqlite3.OperationalError'>, closing connection {'host': '31.11.176.99', 'port': 9444}. Traceback (most recent call last):
  File "spare\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 442, in wait_for
  File "spare\server\server.py", line 533, in wrapped_coroutine
  File "spare\server\server.py", line 526, in wrapped_coroutine
  File "spare\full_node\full_node_api.py", line 244, in request_proof_of_weight
  File "spare\full_node\weight_proof.py", line 77, in get_proof_of_weight
  File "spare\full_node\weight_proof.py", line 119, in _create_proof_of_weight
  File "spare\consensus\blockchain.py", line 695, in get_block_records_at
  File "spare\full_node\block_store.py", line 181, in get_block_records_by_hash
  File "aiosqlite\core.py", line 184, in execute
  File "aiosqlite\core.py", line 129, in _execute
  File "aiosqlite\core.py", line 102, in run
sqlite3.OperationalError: too many SQL variables

**Comment by Ratchanida** [comment]
I have the same message "ERROR Exception: too many SQL variables" and the wallet is not synced as well.  It has been 5 days. I have no idea how to fix the issue : (

**Comment by OldButtKicking** [comment]
Finally fixed it. Shut down app, delete existing wallet db then reinstalled and now it is syncing. Would still say this is a bug I see many people with the same problem.
