### ISSUE TITLE
we need nodes to connect. Just give the ip and port number ?

### ISSUE THREAD

**Issue by sonerbo** [Spare-Network/spare-blockchain#14]

**Comment by 1617176084** [comment]
45:22:5.33:9444

**Comment by walruzperil** [comment]
2021-06-20T19:55:21.266 full_node full_node_server        : ERROR    Exception wss://45:22:5.33:9444/ws, exception Stack: Traceback (most recent call last):
  File "yarl\_url.py", line 170, in __new__
  File "urllib\parse.py", line 169, in port
ValueError: invalid literal for int() with base 10: '22:5.33:9444'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aiohttp\client.py", line 404, in _request
  File "yarl\_url.py", line 174, in __new__
ValueError: Invalid URL: port can't be converted to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "spare\server\server.py", line 361, in start_client
  File "aiohttp\client.py", line 763, in _ws_connect
  File "aiohttp\client.py", line 406, in _request
aiohttp.client_exceptions.InvalidURL: wss://45:22:5.33:9444/ws

**Comment by sonerbo** [comment]
0x91c6475e15089bf36eed0a1caf2702dce353dfbb3ffcd229056172ba47c5e4a0
127.0.0.1
54621/9449
0/0
Wallet
0
0xb4cbc9b45ce0a36da7f78e41992e3616147320b9fa7a39a9e6764221cc76d846
127.0.0.1
54629/9447
0/0
Farmer
0
0xf14126fe2a283fc33ef70e4ee411dfee72bb16c025181951038c66a5d73f4698
46.142.49.1
9444/9444
0/0
Full Node
0
0x2c6f8ca36b11daeda0abc24a364014beef9693534586a2c356c88960d750c862
147.161.80.170
9444/9444
0/0
Full Node
0
0x8bf56370da3c7519db334b9946a108fb804bebf494cc254472c4cdf19eb4aeb3
125.33.57.129
9444/9444
0/0
Full Node
27,679
0xd0960a4d58daaa4af840af50b9cd75a8974d677ebd3034ab343b188c998e4899
190.193.62.247
9444/9444
0/0
Full Node
0
0xa4b032903d07babaa6ccab7f4c3a99b1e0e0b75ce0525d6ba7f5de3048ad5792
123.156.176.188
9444/9444
0/0
Full Node
27,679
0x60b65d8ecd1440aab9f1666d2a8b06f5bc67783b13f13fa9a7bc309ea13abd78
73.51.246.177
9444/9444
0/0
Full Node
27,679

**Comment by miguelcarv1973** [comment]
where is the debug log?

**Comment by miguelcarv1973** [comment]
not synced for long time

**Comment by miguelcarv1973** [comment]
all plots are there, but on full node, windows icon running , but no sync

**Comment by miguelcarv1973** [comment]
now is workinh with your ip..thank you so much

**Comment by walruzperil** [comment]
Nodes found. but sync still 0...

**Comment by sergibarroso** [comment]
> 45:22:5.33:9444

This is not an IPv4 address. Should be `45.22.5.33:9444`

**Comment by mdrodge** [comment]
94.59.216.17 : 9444

**Comment by katolla** [comment]
no matter what node i try to connect to, stuck at 662

**Comment by Arno11** [comment]
Cant even connect with any
