### ISSUE TITLE
spare.rpc.rpc_server errors

### ISSUE THREAD

**Issue by sergibarroso** [Spare-Network/spare-blockchain#14]
I'm running Spare on Debian with Python 3.9. The installation did run smoothly.

But I'm getting some errors on my `debug.log` while running any farm command, such as:

```
2021-06-19T19:09:39.976 wallet spare.rpc.rpc_server       : WARNING  Error while handling message: Traceback (most recent call last):                           │
  File "/home/chia/spare-blockchain/spare/rpc/rpc_server.py", line 81, in inner                                                                                 │
    res_object = await f(request_data)                                                                                                                          │
  File "/home/chia/spare-blockchain/spare/rpc/wallet_rpc_api.py", line 942, in get_farmed_amount                                                                │
    tx_records: List[TransactionRecord] = await self.service.wallet_state_manager.tx_store.get_farming_rewards()                                                │
AttributeError: 'NoneType' object has no attribute 'tx_store' 
```

Also if I run `spare farm summary` I see txstore errors:

```
$ spare farm summary                                                                                                                                            │      Time: Sat Jun 19 2021 18:58:31 CEST                  Height:      21672
Exception from 'wallet' {'error': "'NoneType' object has no attribute 'tx_store'", 'success': False}                                                            │
Farming status: Not synced or not connected to peers                                                                                                            │Estimated network space: 225.724 TiB
Total spare farmed: Unknown                                                                                                                                     │Current difficulty: 1
User transaction fees: Unknown                                                                                                                                  │Current VDF sub_slot_iters: 111673344
Block rewards: Unknown                                                                                                                                          │Total iterations since the start of the blockchain: 55925971671
Last height farmed: Unknown                                                                                                                                     │
[...]
```

Any help would be much appreciated.

**Comment by bg-fr** [comment]
I had the same issue. Try to run this command :
$ `spare wallet show`
(and then press the key S, when asked about backup files)

Then running $ `spare farm summary` should work fine.

Error was discussed here : https://github.com/Chia-Network/chia-blockchain/issues/1750

**Comment by sergibarroso** [comment]
Worked! Thanks @bg-fr
