### ISSUE TITLE
Wallet running on same port as Chia Wallet

### ISSUE THREAD

**Issue by MikeKroell** [Spare-Network/spare-blockchain#6]
When trying to run Wallet:

`(venv) :~/.sparecoin/mainnet/log$ spare start wallet -r
spare_wallet: Traceback (most recent call last):
  File "/home//spare-blockchain/venv/bin/spare_wallet", line 33, in <module>
    sys.exit(load_entry_point('spare-blockchain', 'console_scripts', 'spare_wallet')())
  File "/home//spare-blockchain/spare/server/start_wallet.py", line 92, in main
    return run_service(**kwargs)
  File "/home//spare-blockchain/spare/server/start_service.py", line 234, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home//spare-blockchain/spare/server/start_service.py", line 228, in async_run_service
    return await service.run()
  File "/home//spare-blockchain/spare/server/start_service.py", line 169, in run
    await self.wait_closed()
  File "/home//spare-blockchain/spare/server/start_service.py", line 218, in wait_closed
    await self._rpc_close_task
  File "/home//spare-blockchain/spare/server/start_service.py", line 200, in close_rpc_server
    await (await self._rpc_task)()
  File "/home//spare-blockchain/spare/rpc/rpc_server.py", line 337, in start_rpc_server
    await site.start()
  File "/home//spare-blockchain/venv/lib/python3.8/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 9256): address already in use
`

When querying wallet:

(venv) ~/.sparecoin/mainnet/log$ spare wallet show
Connection error. Check if wallet is running at 9256

Netstat:

`(venv) ~/.sparecoin/mainnet/log$ netstat -tulpn | grep 9256
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:9256          0.0.0.0:*               LISTEN      2688/chia_wallet
`

**Comment by cdgraff** [comment]
I reported the same into the previous release, they fix and now broke again? mmm that look pretty bad...

**Comment by nonotmeiswear** [comment]
I suspect if it's the same as before, change the rpc_port in .sparecoin/mainnet/config/config.yaml
wallet section:
9256 -> 9956

**Comment by MikeKroell** [comment]
> I suspect if it's the same as before, change the rpc_port in .sparecoin/mainnet/config/config.yaml
> wallet section:
> 9256 -> 9956

You can see the service itself is trying to run on 9256 though. I tried looking in the code for the number, but couldn't find it. I gave your suggestion a try anyways and it seems to work.

Question how long of a lag behind finding proofs should it show up in the wallet?

**Comment by nonotmeiswear** [comment]
> > I suspect if it's the same as before, change the rpc_port in .sparecoin/mainnet/config/config.yaml
> > wallet section:
> > 9256 -> 9956
> 
> You can see the service itself is trying to run on 9256 though. I tried looking in the code for the number, but couldn't find it. I gave your suggestion a try anyways and it seems to work.
> 
> Question how long of a lag behind finding proofs should it show up in the wallet?

Given how things have worked out so far, all I can offer you is this:
"What is the length of a string?"

**Comment by MikeKroell** [comment]
> > > I suspect if it's the same as before, change the rpc_port in .sparecoin/mainnet/config/config.yaml
> > > wallet section:
> > > 9256 -> 9956
> > 
> > 
> > You can see the service itself is trying to run on 9256 though. I tried looking in the code for the number, but couldn't find it. I gave your suggestion a try anyways and it seems to work.
> > Question how long of a lag behind finding proofs should it show up in the wallet?
> 
> Given how things have worked out so far, all I can offer you is this:
> "What is the length of a string?"

I'm not following.

**Comment by bg-fr** [comment]
> I suspect if it's the same as before, change the rpc_port in .sparecoin/mainnet/config/config.yaml
> wallet section:
> 9256 -> 9956

Worked for me! Thanks!

**Comment by Jsewill** [comment]
I've submitted a pull request (#104) to correct this.
