### ISSUE TITLE
harvester network error

### ISSUE THREAD

**Issue by BianKo666niglio** [Spare-Network/spare-blockchain#67]
my harvester network is connected but every second it change te port xxxx/9448 and the counting connection is still 0/0.

in debug file I have this error

2021-06-21T22:08:10.369 harvester harvester_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 9447}. Traceback (most recent call last):
  File "spare\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

**Comment by MikaelTeoh** [comment]
i have the same error

**Comment by MikaelTeoh** [comment]
anyone please? how to fix this error
