### ISSUE TITLE
over 1000 plots - no winnings for a week (estimated is 1-2 days)

### ISSUE THREAD

**Issue by gamilevin** [Spare-Network/spare-blockchain#99]
Hi, 

I'm newbie with networking and afraid I'm missing winning due to this issue.
So since I have a complex network architecture at home I haven't done the port forwarding.
Can it effect my winnings?

My Node seem to be synced, it's just that I don't see timestamps for all hashes, is that OK?
![spare1](https://user-images.githubusercontent.com/63460575/124348199-39e76780-dbf1-11eb-86d4-9dd99dc0b6c9.png)

This is how my farm looks like. Is it OK? 

![spare2](https://user-images.githubusercontent.com/63460575/124348203-3e138500-dbf1-11eb-9f47-c9f0b4042756.png)

Would appreciate the assistance of pointing out my problem.
I can dig in  the debug.log if needed.

Thanks

**Comment by Unclevasil** [comment]
I have same Problem

**Comment by Orantz-vn** [comment]
I have the same problem, several days ago.
I tried deleting the database but nothing :(

**Comment by tecknikos** [comment]
Same thing as well, after restarting client ive noticed the sync is way behind. This happens continuously. Waist of time...

**Comment by LimakKAAM** [comment]
Hi, 14 day miming I have 96 spare 
1633 plot

**Comment by SkeletonFX** [comment]
245 plots, 0 spare too

**Comment by Orantz-vn** [comment]
35 / 5000
Resultados de traducción
hello, I have checked my log and I have seen : ?¿
2021-07-05T21:55:40.326 full_node full_node_server        : ERROR    Exception: Error short batch syncing, could not fetch block at height 77206 <class 'ValueError'>, closing connection {'host': '62.99.25.218', 'port': 7444}. Traceback (most recent call last):
  File "spare\server\server.py", line 536, in api_call
  File "asyncio\tasks.py", line 414, in wait_for
  File "spare\server\server.py", line 533, in wrapped_coroutine
  File "spare\server\server.py", line 526, in wrapped_coroutine
  File "spare\full_node\full_node_api.py", line 104, in new_peak
  File "spare\full_node\full_node.py", line 386, in new_peak
  File "spare\full_node\full_node.py", line 237, in short_sync_batch
ValueError: Error short batch syncing, could not fetch block at height 77206

2021-07-05T21:55:40.411 full_node full_node_server        : WARNING  Banning xx.xx.xx.xx for 10 seconds

**Comment by sergiosurvival** [comment]
comprobar que tengan la misma billera en granja y wallet se cambian solas.....

**Comment by sergiosurvival** [comment]
ami se me a perdido un monto por eso....de forks.green a spare como se cambian solas las wallets perdi este monto solo me llego el ultimo...0.05 spare....
![2021-09-01](https://user-images.githubusercontent.com/83919237/131705537-a7504a29-0078-4fb4-bf15-e18260ccd173.png)

**Comment by sergiosurvival** [comment]
12 perdido
1 perdido
0.05 perdido

**Comment by otraver** [comment]
I have the same problem.
Farming with 1110 plots 24h/7d from June, only 4 spares.
I winned 2 XCH, 14 XFX, 5500 CGN and only 4 SPARE.
![imagen](https://user-images.githubusercontent.com/51640409/132221436-d985f59b-581f-4af8-8197-2e17190f3d29.png)

Tengo el mismo problema.
Farmeando con 1110 plots 24/7 desde que conocí este fork 14 XFX, 5500 CGN y solo 4 SPARE.
He comprobado la billetera y es la misma tanto en la granja como en wallet.
He ganado 2 XCH,
